/* WORLD 06 · Excretory System · original activities guided by the supplied Grade 10 lesson. */
(()=>{'use strict';
const titles=['Where wastes go','Inside a kidney','The filtration gate','Keep the useful parts','Balance during exercise','Kidney care detective'];
const lessons=[
 {goal:'Identify organs that remove wastes and trace urine out of the body.',terms:'lungs · skin · kidneys · ureters · bladder · urethra',text:'Cells produce wastes during daily activity. The lungs release carbon dioxide, the skin releases some water and salts in sweat, and the liver breaks down excess amino acids and produces bile, and the kidneys remove urea and other dissolved wastes while adjusting water and salts. Urine travels from the kidneys through the ureters, collects in the urinary bladder, and leaves through the urethra.',clue:'A ureter leads from kidney to bladder; the urethra leads from bladder to outside.',checks:[['Which organ primarily releases carbon dioxide?',['Kidneys','Lungs','Bladder'],1,'The lungs exhale carbon dioxide.'],['After leaving a kidney, urine enters the…',['Ureter','Renal artery','Urethra'],0,'A ureter carries urine toward the bladder.'],['Which tube carries urine out from the bladder?',['Renal vein','Ureter','Urethra'],2,'The urethra carries urine out of the body.']]},
 {goal:'Locate the cortex, medulla and pelvis in a kidney.',terms:'renal cortex · renal medulla · renal pelvis · renal artery · renal vein',text:'The bean-shaped kidneys have an outer renal cortex and inner renal medulla. Blood arrives through a renal artery and leaves through a renal vein. Urine produced within the kidney drains toward the renal pelvis and then into a ureter. Select the Kidney cutaway in the 3D viewer to inspect these regions.',clue:'Cortex outside, medulla inside, pelvis collects urine.',checks:[['The outer kidney region is the…',['Renal pelvis','Renal cortex','Ureter'],1,'The renal cortex is the outer region.'],['Where does urine collect before the ureter?',['Renal pelvis','Renal artery','Glomerulus'],0,'The renal pelvis funnels urine toward the ureter.'],['Which vessel brings blood to the kidney?',['Renal vein','Urethra','Renal artery'],2,'The renal artery brings blood into a kidney.']]},
 {goal:'Explain what crosses the glomerular filter.',terms:'nephron · glomerulus · Bowman’s capsule · filtration · urea',text:'Each kidney contains many microscopic nephrons. In a nephron, pressure drives water and small dissolved substances, including urea, from glomerular capillaries into Bowman’s capsule. Blood cells and most large proteins normally remain in the blood. The collected fluid is called filtrate; it is not yet the final urine.',clue:'Small dissolved substances can pass into filtrate; cells and large proteins usually stay in blood.',checks:[['Which structure receives the first filtrate?',['Bladder','Bowman’s capsule','Ureter'],1,'Bowman’s capsule receives fluid filtered at the glomerulus.'],['Which normally remains in blood?',['Red blood cells','Water','Urea'],0,'Blood cells are too large to pass through the healthy filter.'],['Is filtrate already final urine?',['Yes, nothing changes afterward','It is made in the bladder','No, useful material is still reabsorbed'],2,'Tubules change filtrate before it becomes urine.']]},
 {goal:'Sort what returns to blood from what leaves in urine.',terms:'reabsorption · renal tubule · loop of Henle · collecting duct',text:'Filtrate flows through the renal tubule, including the loop of Henle, and then toward a collecting duct. Much water and useful dissolved material such as glucose return to surrounding capillaries by reabsorption. How much water is reclaimed is adjusted by the hormone ADH, which acts mainly on the collecting duct. Excess water, salts and dissolved wastes remain or are added to the tubule and leave in urine. The collecting ducts drain toward the renal pelvis.',clue:'Reabsorption returns useful substances to blood; urine carries the remaining waste away.',checks:[['Glucose in filtrate is usually…',['Returned to blood','Stored in bladder as sugar','Exhaled'],0,'Useful glucose is normally reabsorbed.'],['Where does final urine flow after collecting ducts?',['Into renal pelvis','Into glomerulus','Into renal artery'],0,'It travels toward the renal pelvis.'],['The loop of Henle helps the kidney…',['Breathe','Conserve water','Pump blood'],1,'The loop builds the concentration gradient; ADH then controls how much water the collecting duct returns.']]},
 {goal:'Connect kidney regulation with exercise and homeostasis.',terms:'homeostasis · water balance · salts · blood pH · exercise',text:'Kidneys adjust how much water and salts leave the body and help regulate blood acid-base balance. During exercise, breathing releases more carbon dioxide, sweat carries away some water and salts, and kidneys can conserve water when fluid is scarce. These systems work together to keep internal conditions suitable for cells.',clue:'Sweating and breathing change losses; kidneys adjust the composition of urine over time.',checks:[['During exercise, which organ releases more CO₂ as breathing increases?',['Skin','Lungs','Bladder'],1,'The lungs exhale carbon dioxide.'],['If the body needs to conserve water, kidneys can…',['Reabsorb more water','Stop filtering blood forever','Turn urea into oxygen'],0,'More water can return to blood, leaving less in urine.'],['Maintaining stable internal conditions is called…',['Filtration','Evaporation','Homeostasis'],2,'Water, salts and acid-base balance are part of homeostasis.']]},
 {goal:'Interpret common kidney problems and compare treatments.',terms:'kidney stone · nephritis · infection · dialysis · transplant',text:'Kidney stones are hard mineral deposits that may obstruct urine flow. Nephritis involves kidney inflammation, often affecting glomeruli. Infection can spread from the urinary tract toward the kidneys. If kidneys cannot filter sufficiently, dialysis uses a machine to remove wastes from blood; a transplant replaces kidney function with a donated kidney. These classroom cases show mechanisms, not diagnoses.',clue:'A stone is a solid deposit; dialysis filters blood outside the body.',checks:[['A kidney stone is…',['A hard mineral deposit','A normal nephron','A red blood cell'],0,'Minerals can crystallize into a solid stone.'],['Nephritis involves…',['More alveoli','Kidney inflammation','Extra ureters'],1,'Inflammation may affect glomeruli and kidney tissue.'],['Dialysis helps by…',['Replacing the lungs','Making a kidney stone','Filtering wastes from blood'],2,'Dialysis removes wastes when kidney function is insufficient.']]}
];
const labs=[
 {title:'Waste-route relay',intro:'Send each waste or fluid to the organ or route that handles it.',tasks:[['A cell produces carbon dioxide. Where does it leave?',['Skin','Lungs','Bladder'],1,'The lungs exhale carbon dioxide.'],['Which route takes urine from kidney to bladder?',['Urethra','Renal vein','Ureter'],2,'A ureter connects a kidney to the bladder.'],['Where is urine stored before release?',['Bladder','Renal artery','Lung'],0,'The urinary bladder stores urine.']]},
 {title:'Kidney cutaway scanner',intro:'Read each location clue and identify the kidney region.',tasks:[['Outer filtering region',['Renal pelvis','Renal cortex','Ureter'],1,'The cortex is outermost.'],['Inner region with tubules and pyramids',['Renal medulla','Bladder','Renal vein'],0,'The medulla lies inside the cortex.'],['Central funnel leading toward a ureter',['Glomerulus','Renal artery','Renal pelvis'],2,'The pelvis collects urine.']]},
 {title:'Filtration gate',intro:'Decide which items enter Bowman’s capsule through a healthy filter.',tasks:[['Water',['Stays in blood only','Enters filtrate'],1,'Water crosses the filter.'],['Red blood cells',['Remain in blood','Enter filtrate normally'],0,'Cells normally remain in blood.'],['Urea dissolved in water',['Enters filtrate','Remains trapped in blood'],0,'Urea is among the small dissolved wastes filtered.'],['Most large blood proteins',['Pass into urine','Remain in blood'],1,'Large proteins normally stay in circulation.']]},
 {title:'Reabsorption rescue',intro:'Choose the usual destination for each substance after filtration.',tasks:[['Useful glucose',['Bladder','Back into blood'],1,'Glucose is usually reclaimed.'],['Much filtered water',['Back into blood','Always lost entirely'],0,'Much filtered water is reabsorbed.'],['Excess dissolved waste',['Returned to blood on purpose','Remains for urine'],1,'Waste remains to be excreted.'],['Final urine after a collecting duct',['Renal pelvis','Glomerulus'],0,'Collecting ducts drain toward the renal pelvis.']]},
 {title:'Exercise balance challenge',intro:'Connect changes during a school run to the organ that responds.',tasks:[['A runner breathes harder and makes more CO₂. Which system removes it?',['Respiratory','Skeletal','Integumentary'],0,'The lungs exhale CO₂.'],['Sweat carries away water and salts. Which system makes the sweat?',['Renal pelvis','Integumentary','Muscular'],1,'Sweat glands are in the skin.'],['After fluid loss, which organ can conserve water in urine?',['Kidney','Trachea','Biceps'],0,'Kidneys can reabsorb more water.']]},
 {title:'Kidney care detective',intro:'Use the evidence to distinguish a mechanism from a treatment.',tasks:[['Hard mineral material obstructs a urinary route.',['Nephritis','Kidney stone','Dialysis'],1,'A stone is a crystallized deposit.'],['Inflammation affects glomeruli.',['Nephritis','Healthy reabsorption','Transplant'],0,'Nephritis can involve glomerular inflammation.'],['A machine removes wastes when kidney filtering is severely reduced.',['Ureter','Dialysis','Sweating'],1,'Dialysis filters blood.'],['A donated organ takes over kidney work.',['Kidney transplant','Kidney stone','Urethra'],0,'A transplant uses a donor kidney.']]}
];
const finalStages=[
 ['Which three organs contribute directly to excretion?',['Lungs, skin and kidneys','Bones, biceps and cartilage'],0,'The lungs, skin and kidneys remove different wastes.'],
 ['Follow urine after it leaves a kidney.',['Ureter → bladder → urethra','Urethra → artery → bladder'],0,'Urine follows the ureter, bladder and urethra.'],
 ['Which kidney region is on the outside?',['Medulla','Cortex'],1,'The cortex is outer.'],
 ['At the glomerulus, which stays in the blood?',['Blood cells','Water and urea'],0,'Cells normally remain within the vessels.'],
 ['Where does filtrate first collect?',['Bowman’s capsule','Urinary bladder'],0,'The capsule surrounds the glomerulus.'],
 ['What does reabsorption return?',['Useful water and solutes to blood','All waste into the renal artery'],0,'Useful material returns from tubule to blood.'],
 ['Exercise leads to sweating. What can kidneys adjust?',['Water lost in urine','Number of bones'],0,'Kidneys adjust water balance.'],
 ['When kidneys filter inadequately, dialysis…',['Filters wastes from blood','Creates new nephrons immediately'],0,'Dialysis provides an artificial filtering route.']
];lessons.forEach(l=>{l.checks=l.checks.map(mixQ)});finalStages.forEach((q,i)=>finalStages[i]=mixQ(q));

function progress(){if(!state.excretory||typeof state.excretory!=='object')state.excretory={};const p=state.excretory;p.done=Array.isArray(p.done)?p.done:[];p.steps=p.steps&&typeof p.steps==='object'?p.steps:{};p.weak=Array.isArray(p.weak)?p.weak:[];return p}
const done=id=>!!progress().steps[id];
function step(id,xp){if(done(id))return;progress().steps[id]=true;save();reward('exc-'+id,xp)}
const percent=()=>Math.round((progress().done.length+Number(!!progress().mastery))/7*100);
function landing(){const p=progress();layout(`<div class="exc-world"><section class="exc-hero"><div><span class="eyebrow">SYSTEM 06 — EXCRETORY SYSTEM</span><h1>The Balance Mission</h1><p>Follow wastes out of the body, enter a kidney, pass the nephron filtration gate and rescue useful water before it becomes urine.</p><a class="btn" href="#excretory/mission/${Math.min(6,p.done.length+1)}">${p.done.length?'Continue':'Begin'} the mission →</a><p class="exc-progress">${p.done.length}/6 missions · ${percent()}% complete</p></div><div class="exc-hero-art"><img src="assets/excretory-kidney-hero.webp" alt="Kidney cutaway showing the cortex, medullary pyramids, collecting region, renal blood vessels, and ureter" width="720" height="900" loading="eager"></div></section>${bodyAtlasMarkup('excretory')}<section class="panel exc-intro"><span class="eyebrow">EXPEDITION MAP</span><h2>Six discoveries. One balanced body.</h2><p>Solve the hands-on challenge and three checks in each mission to unlock the next. Explore the 3D urinary organs, kidney cutaway and enlarged nephron as you go.</p></section><div class="resp-grid">${titles.map((title,i)=>`<article class="panel resp-card ${i>p.done.length?'resp-locked':''}"><span class="eyebrow">MISSION ${String(i+1).padStart(2,'0')} ${p.done.includes(i+1)?'· COMPLETE':''}</span><h3>${title}</h3><p>${lessons[i].goal}</p>${i<=p.done.length?`<a class="btn secondary" href="#excretory/mission/${i+1}">${p.done.includes(i+1)?'Replay':'Explore'} →</a>`:'<span class="exc-locked">Finish the previous mission to unlock</span>'}</article>`).join('')}</div><section class="panel resp-finale"><div><span class="eyebrow">FINAL CHALLENGE</span><h2>Restore the balance</h2><p>Combine your six discoveries to earn the Excretory System Key.</p></div>${p.done.length===6?'<a class="btn" href="#excretory/mastery">Enter final challenge →</a>':'<span>Complete all six missions to unlock</span>'}</section></div>`);window.mountBodyAtlas?.('excretory')}
function lab(n){const d=labs[n-1];return `<section class="panel exc-lab"><span class="eyebrow">INTERACTIVE LAB</span><h2>${d.title}</h2><p>${d.intro}</p><div class="exc-lab-top"><span id="exc-lab-step">${done(`${n}-lab`)?'Discovery saved · replay to practice':`STAGE 1 / ${d.tasks.length}`}</span><span class="exc-sparks" aria-hidden="true">✧ ✦ ✧</span></div><div id="exc-lab-scene" class="exc-lab-scene" role="group" aria-label="${d.title}"></div><div id="exc-lab-feedback" class="exc-lab-feedback" role="status"></div></section>`}
function mission(n){const p=progress();if(!Number.isInteger(n)||n<1||n>6||n>1&&!p.done.includes(n-1)){location.hash='excretory';return}const d=lessons[n-1];layout(`<div class="exc-world"><a class="textlink" href="#excretory">← The Balance Mission</a><div class="resp-mission-header"><span class="eyebrow">SYSTEM 06 · MISSION ${String(n).padStart(2,'0')}</span><h1>${titles[n-1]}</h1><p>${d.goal}</p></div><div class="resp-columns"><div><section class="panel resp-lesson"><span class="eyebrow">LEARN THE SCIENCE</span><h2>The idea</h2><p>${d.text}</p><p class="hint"><strong>Remember:</strong> ${d.clue}</p></section>${lab(n)}<section class="panel resp-checks"><span class="eyebrow">CHECK YOUR UNDERSTANDING</span><h2>Three checks</h2>${d.checks.map((q,i)=>`<div class="resp-question" data-exc-question="${i}"><h3>${i+1}. ${q[0]}</h3><div class="resp-choices">${q[1].map((a,j)=>`<button type="button" data-choice="${j}" ${done(`${n}-q${i}`)?'disabled':''}>${a}</button>`).join('')}</div><div class="resp-feedback" role="status">${done(`${n}-q${i}`)?'✓ '+q[3]:''}</div></div>`).join('')}<div id="exc-finish"></div></section></div><aside class="panel resp-aside"><h3>Mission guide</h3><p><strong>Goal:</strong> ${d.goal}</p><p><strong>Keywords:</strong> ${d.terms}</p><p><strong>Clue:</strong> ${d.clue}</p><a class="textlink" href="#excretory">Open the 3D explorer →</a></aside></div></div>`);
const finish=()=>{if(done(`${n}-lab`)&&d.checks.every((_,i)=>done(`${n}-q${i}`))){if(!p.done.includes(n)){p.done.push(n);save();reward('exc-mission-'+n,25)}document.getElementById('exc-finish').innerHTML=`<div class="feedback">Mission complete. Balance fragment ${n}/6 secured. <a href="#excretory/${n===6?'mastery':'mission/'+(n+1)}">${n===6?'Final challenge':'Next mission'} →</a></div>`}};
let current=0;const task=labs[n-1].tasks;const draw=()=>{const q=task[current],scene=document.getElementById('exc-lab-scene');document.getElementById('exc-lab-step').textContent=`STAGE ${current+1} / ${task.length}`;scene.innerHTML=`<h3>${q[0]}</h3><div class="resp-choices">${q[1].map((a,j)=>`<button type="button" data-exc-choice="${j}">${a}</button>`).join('')}</div>`;scene.querySelectorAll('[data-exc-choice]').forEach(b=>b.onclick=()=>{const good=+b.dataset.excChoice===q[2];document.getElementById('exc-lab-feedback').textContent=(good?'Correct. ':'Try again. ')+q[3];scene.classList.toggle('exc-error',!good);if(!good)return;scene.classList.remove('exc-error');b.classList.add('resp-correct');scene.querySelectorAll('button').forEach(x=>x.disabled=true);if(current===task.length-1){step(`${n}-lab`,20);document.getElementById('exc-lab-step').textContent='✓ DISCOVERY SAVED';finish()}else{const next=document.createElement('button');next.type='button';next.className='btn secondary exc-next';next.textContent='Next stage →';next.onclick=()=>{current++;document.getElementById('exc-lab-feedback').textContent='';draw()};scene.append(next)}})};draw();
document.querySelectorAll('[data-exc-question]').forEach(el=>{const i=+el.dataset.excQuestion,q=d.checks[i],weakId=n+'-q'+i;el.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const good=+b.dataset.choice===q[2],tries=+el.dataset.tries||0;if(!good)el.dataset.tries=String(tries+1);el.querySelector('.resp-feedback').textContent=good?'Correct. '+q[3]:(tries<1?'Not yet. Re-read the mission guide, then try again.':'Look again. '+q[3]);el.classList.toggle('resp-wrong',!good);const pw=progress();if(good){pw.weak=pw.weak.filter(x=>x!==weakId)}else if(!pw.weak.includes(weakId)){pw.weak.push(weakId)}save();if(good){b.classList.add('resp-correct');el.querySelectorAll('button').forEach(x=>x.disabled=true);step(`${n}-q${i}`,7);finish()}})});finish()}
function mastery(){const p=progress();if(p.done.length<6){location.hash='excretory';return}layout(`<div class="exc-world"><a class="textlink" href="#excretory">← The Balance Mission</a><div class="resp-mission-header"><span class="eyebrow">SYSTEM 06 · FINAL CHALLENGE</span><h1>Restore the balance</h1><p>Reconnect waste removal, filtration, reabsorption and fluid balance.</p></div><section class="panel resp-checks">${finalStages.map((q,i)=>`<div class="resp-question" data-exc-final="${i}"><span class="eyebrow">STAGE ${i+1}/8</span><h3>${q[0]}</h3><div class="resp-choices">${q[1].map((a,j)=>`<button type="button" data-choice="${j}" ${done('final-'+i)?'disabled':''}>${a}</button>`).join('')}</div><div class="resp-feedback" role="status">${done('final-'+i)?'✓ '+q[3]:''}</div></div>`).join('')}<div id="exc-mastered"></div></section></div>`);const finish=()=>{if(finalStages.every((_,i)=>done('final-'+i))){if(!p.mastery){p.mastery=true;save();reward('exc-key',50)}document.getElementById('exc-mastered').innerHTML='<div class="feedback"><h2>Balance restored!</h2><p>You earned the Excretory System Key.</p><a class="btn secondary" href="#excretory">Explore the world again →</a></div>'}};document.querySelectorAll('[data-exc-final]').forEach(el=>{const i=+el.dataset.excFinal,q=finalStages[i];el.querySelectorAll('button').forEach(b=>b.onclick=()=>{const good=+b.dataset.choice===q[2];el.querySelector('.resp-feedback').textContent=(good?'Correct. ':'Try again. ')+q[3];el.classList.toggle('resp-wrong',!good);if(good){b.classList.add('resp-correct');el.querySelectorAll('button').forEach(x=>x.disabled=true);step('final-'+i,8);finish()}})});finish()}
const priorPortal=portal;portal=function(i){if(i!==5)return priorPortal(i);const p=percent(),s=systems[5];return `<article class="portal world-portal playable" data-card="5" style="--system-color:${s[3]}"><button class="system-select" data-system="5" aria-pressed="false" aria-label="Select Excretory System"><span class="world-card-top"><span class="system-icon">${systemIcon(5)}</span><span class="world-index">WORLD 06</span></span><span class="world-card-name">FILTER</span><span class="scientific-name">Excretory System</span><span class="ready-label">${p?'Exploration in progress':'Ready to explore'}</span><span class="progress-meta"><span>${p}% complete</span><span>Six missions</span></span><span class="bar"><i style="width:${p}%"></i></span></button><a class="btn enter-world" href="#excretory">Enter World →</a></article>`};
const priorHighlight=highlightSystem;highlightSystem=function(i){priorHighlight(i);if(i!==5)return;const panel=document.getElementById('selected-system-panel');panel.innerHTML='<div class="eyebrow">THE BALANCE MISSION</div><h2>Excretory System</h2><p>Trace wastes, inspect kidneys and nephrons, and restore fluid balance.</p><a class="btn selected-enter" href="#excretory">Enter the Balance Mission →</a><button class="clear-selection" aria-label="Show all body systems">Show all systems</button>';panel.querySelector('.clear-selection').onclick=resetSystem};
const priorSelectSystem=selectSystem;selectSystem=function(i){priorSelectSystem(i);if(i===5){const tip=document.getElementById('anatomy-tooltip');if(tip)tip.textContent='Enter the Balance Mission'}};
const priorHome=home;home=function(){priorHome();const j=document.querySelector('[data-journey="5"]');if(j&&!j.querySelector('.journey-playable'))j.insertAdjacentHTML('beforeend','<b class="journey-playable">PLAYABLE</b>')};
const priorDashboard=dashboard;dashboard=function(){priorDashboard();const p=progress(),section=document.createElement('section');section.className='panel spacer';section.innerHTML=`<div class="eyebrow">SYSTEM 06 — EXCRETORY SYSTEM</div><h2>The Balance Mission</h2><p>${p.done.length}/6 missions complete · ${p.mastery?'System Key earned':'Final challenge awaits'}</p><div class="bar"><i style="width:${percent()}%"></i></div><a class="btn" href="#excretory">Continue the Balance Mission →</a>`;const weakIds=p.weak||[];if(weakIds.length){const rv=document.createElement('p');rv.className='note';rv.innerHTML='Revisit: '+weakIds.map(id=>{const a=id.split('-q').map(Number);return '<a class="textlink" href="#excretory/mission/'+a[0]+'">'+lessons[a[0]-1].checks[a[1]][0]+'</a>'}).join(' · ');section.append(rv)}
document.getElementById('main').append(section);const reset=document.getElementById('reset');if(reset){const before=reset.onclick;reset.onclick=()=>{before();const yes=document.getElementById('confirm-reset');if(yes){const confirm=yes.onclick;yes.onclick=()=>{state.excretory={done:[],steps:{},mastery:false};confirm()}}}}};
const priorBadges=badges;badges=function(){priorBadges();const p=progress();document.getElementById('main').insertAdjacentHTML('beforeend',`<section class="panel spacer"><h2>Balance Mission discoveries</h2><div class="resp-grid">${titles.map((title,i)=>`<a class="badge ${p.done.includes(i+1)?'':'locked'}" href="#excretory/mission/${i+1}"><span>◈</span><h3>${title}</h3><p>${p.done.includes(i+1)?'Earned':'Complete mission '+(i+1)}</p></a>`).join('')}</div><p>${p.mastery?'Excretory System Key earned.':'Complete all missions and the final challenge to earn the System Key.'}</p></section>`)};
const priorInfo=info;info=function(r){priorInfo(r);if(r==='sources')document.querySelector('#main .sourcelist')?.insertAdjacentHTML('beforeend','<li><b>UAE Inspire Science Biology · Grade 10 General · Excretory System, supplied lesson pp. 40–44.</b><br>Organs of excretion, renal structure, nephron filtration and reabsorption, kidney disorders and treatments. Original 3D teaching model is simplified; textbook figures are not reproduced.</li>')};
const priorRoute=route;window.removeEventListener('hashchange',priorRoute);route=function(){const h=location.hash.slice(1);if(h==='excretory')landing();else if(h.startsWith('excretory/mission/'))mission(Number(h.split('/')[2]));else if(h==='excretory/mastery')mastery();else priorRoute();window.scrollTo(0,0)};window.addEventListener('hashchange',route);route();
})();
