/* WORLD 04 · Respiratory System — original classroom activities based on supplied lesson. */
(()=>{'use strict';
const titles=['Why we breathe','Follow the air','At the alveolus','The breathing engine','Oxygen on the move','Protect the exchange'];
const lessons=[
 {goal:'Separate ventilation, gas exchange and cellular respiration.',terms:'ventilation · external respiration · internal respiration · cellular respiration · ATP',text:'Breathing moves air into and out of the lungs. At the alveoli, oxygen enters blood and carbon dioxide leaves it. At body cells, oxygen leaves blood while carbon dioxide enters it. Inside cells, cellular respiration uses oxygen and glucose to release usable energy (ATP), producing carbon dioxide and water.',mis:'Air moving into a lung is ventilation; it is not the same event as cellular respiration.',checks:[['What is ventilation?',['Air moving into and out of lungs','Cells releasing ATP','Oxygen crossing a capillary'],0,'Ventilation is the mechanical movement of air.'],['Where does external respiration occur?',['Alveoli and lung capillaries','Inside mitochondria','At the diaphragm'],0,'External respiration exchanges gases between air and lung blood.'],['A muscle cell uses oxygen and glucose. The result includes…',['ATP, carbon dioxide and water','Only oxygen','Only glucose'],0,'Cellular respiration makes usable ATP and produces carbon dioxide and water.']]},
 {goal:'Trace an inhaled breath and explain how the airways protect the lungs.',terms:'nasal passages · cilia · pharynx · larynx · trachea · bronchi · bronchioles',text:'Air enters through the nose or mouth. Nasal passages warm and moisten it; hair and mucus trap particles. Cilia help sweep trapped material toward the throat. Air passes the pharynx and larynx, enters the trachea, splits into the main bronchi and travels through smaller bronchioles toward the alveoli.',mis:'Bronchi lead into lungs; bronchioles are their smaller branches.',checks:[['What comes just after the trachea?',['Two main bronchi','Alveoli','Nasal passages'],0,'The trachea divides into the main bronchi.'],['Which pair helps remove inhaled particles?',['Mucus and cilia','Alveoli and capillaries','Diaphragm and ribs'],0,'Mucus traps particles and cilia sweep material toward the throat.'],['Why do nasal passages help breathing?',['They warm, moisten and filter air','They pump oxygen into blood','They make ATP'],0,'Nasal passages condition incoming air.']]},
 {goal:'Use gradients and thin walls to explain gas exchange.',terms:'alveolus · capillary · diffusion · oxygen · carbon dioxide',text:'Millions of tiny alveoli provide a large surface for exchange. Their moist, very thin walls sit next to equally thin capillary walls. Oxygen moves from alveolar air into blood; carbon dioxide moves from blood into an alveolus to be exhaled. Diffusion moves each gas down its concentration gradient.',mis:'The gases travel in opposite directions across the same exchange boundary.',checks:[['Which gas diffuses from air into lung blood?',['Oxygen','Carbon dioxide','Glucose'],0,'Oxygen moves from alveolar air into capillary blood.'],['Carbon dioxide crosses from…',['Capillary blood to alveolar air','Alveolar air to blood','The diaphragm to blood'],0,'Carbon dioxide enters the alveolus and leaves on exhalation.'],['Why are alveolar walls thin?',['To shorten the diffusion distance','To pump the lungs','To stop all water'],0,'A thin exchange barrier helps diffusion.']]},
 {goal:'Predict air movement when the diaphragm changes chest volume.',terms:'diaphragm · contraction · relaxation · pressure · inhalation · exhalation',text:'Inhaling: the diaphragm contracts and moves downward, the chest expands, pressure inside the lungs falls below outside air pressure and air flows in. Exhaling at rest: the diaphragm relaxes and rises, chest volume decreases, pressure rises and air flows out. The rib cage also moves during breathing.',mis:'Air does not enter because the diaphragm pushes it into the lungs; air flows down a pressure difference.',checks:[['During inhalation the diaphragm…',['Contracts and moves down','Relaxes and moves up','Stops moving'],0,'Contraction flattens and lowers the diaphragm.'],['When chest volume increases, pressure inside generally…',['Falls and air enters','Rises and air enters','Does not change'],0,'The pressure drop draws air inward.'],['At rest, exhalation accompanies…',['Diaphragm relaxation and decreasing volume','Diaphragm contraction and rising volume','Oxygen turning to carbon dioxide'],0,'Relaxation lets the diaphragm rise and volume decrease.']]},
 {goal:'Connect exchange in the lungs to exchange at working body cells.',terms:'pulmonary capillary · red blood cell · tissue capillary · exercise',text:'The circulatory system carries oxygen from lung capillaries to body tissues. At tissue capillaries oxygen enters cells and carbon dioxide enters blood. Blood returns carbon dioxide to the lungs. During exercise, working muscle cells need more ATP; breathing and circulation usually increase to meet demand and clear carbon dioxide.',mis:'Oxygen changes direction at the lung versus tissue exchange sites.',checks:[['At a muscle cell, oxygen travels…',['Blood → cell','Cell → blood','Alveolus → diaphragm'],0,'At tissue capillaries oxygen leaves blood for cells.'],['Where does carbon dioxide made by muscle go?',['Cell → blood → lungs','Cell → arteries → cells only','Directly into nasal hairs'],0,'Blood carries carbon dioxide back to the lungs.'],['During exercise, breathing usually increases because…',['Energy demand and carbon dioxide production rise','Alveoli disappear','The trachea becomes the heart'],0,'Higher energy demand is linked to more gas exchange.']]},
 {goal:'Compare common respiratory problems by their affected structure.',terms:'asthma · bronchitis · emphysema · pneumonia · lung cancer',text:'Asthma can narrow inflamed airways, making airflow difficult. Bronchitis inflames the bronchi and may increase mucus. Emphysema damages alveolar walls, reducing exchange surface. Pneumonia can fill alveoli with fluid, making exchange harder. Lung cancer is uncontrolled cell growth in lung tissue; smoking and vaping are the main preventable causes. Avoiding smoke protects airways and lung tissue.',mis:'Different conditions affect airflow or gas exchange in different ways; a symptom is not a diagnosis.',checks:[['Which condition damages alveolar walls?',['Emphysema','Bronchitis','Asthma'],0,'Emphysema reduces the effective alveolar exchange surface.'],['Fluid filling alveoli can occur in…',['Pneumonia','A healthy inhalation','Normal ciliary sweeping'],0,'Fluid at the exchange surface makes diffusion harder.'],['Bronchitis mainly affects the…',['Bronchi','Diaphragm tendon','Red blood cell nucleus'],0,'Bronchitis inflames the bronchi and may increase mucus.']]}
];
const labs=[
 ['Three linked events','Choose an event to see what moves and where.',[['Ventilation','Air travels between the atmosphere and lungs.'],['External exchange','Oxygen enters lung blood; carbon dioxide enters alveolar air.'],['Cellular respiration','Cells use oxygen and glucose to release ATP.']]],
 ['Airway expedition','Build the route in order, starting from the nose or mouth.',[['Nose or mouth','Air enters.'],['Pharynx','Shared passage behind the nose and mouth.'],['Larynx','Air passes the voice box.'],['Trachea','One tube toward the chest.'],['Bronchi','A branch to each lung.'],['Bronchioles','Fine branches lead onward.'],['Alveoli','Tiny sacs where gas exchange happens.']]],
 ['Alveolus exchange','Choose a gas and set where its concentration is higher.',[['Oxygen','Alveolar air → capillary blood.'],['Carbon dioxide','Capillary blood → alveolar air.']]],
 ['Breathing simulator','Change diaphragm motion and observe chest volume, pressure and airflow.',[['Contract · down','Chest volume increases; pressure falls; air enters.'],['Relax · up','Chest volume decreases; pressure rises; air leaves.']]],
 ['Two exchange sites','Trace oxygen outward and carbon dioxide on its return.',[['Lung capillary','O₂ goes into blood; CO₂ goes into alveolus.'],['Tissue capillary','O₂ goes into cell; CO₂ goes into blood.']]],
 ['Spot the affected structure','Match each case to a part of the respiratory system.',[['Narrowed airways','Asthma: bronchioles can narrow.'],['More mucus in bronchi','Bronchitis affects bronchial passages.'],['Damaged air sacs','Emphysema damages alveolar walls.'],['Fluid in air sacs','Pneumonia can fill alveoli with fluid.']]]
];lessons.forEach(l=>{l.checks=l.checks.map(mixQ)});

function progress(){if(!state.respiratory||typeof state.respiratory!=='object')state.respiratory={};const p=state.respiratory;p.done=Array.isArray(p.done)?p.done:[];p.steps=p.steps&&typeof p.steps==='object'?p.steps:{};p.weak=Array.isArray(p.weak)?p.weak:[];return p}
const completed=id=>!!progress().steps[id];
function step(id,xp){if(completed(id))return;progress().steps[id]=true;save();reward('resp-'+id,xp)}
const percent=()=>Math.round((progress().done.length+Number(!!progress().mastery))/7*100);
function questions(n){return lessons[n-1].checks.map((q,i)=>{let id=`${n}-q${i}`;return `<div class="resp-question" data-question="${id}"><h3>${i+1}. ${esc(q[0])}</h3><div class="resp-choices">${q[1].map((option,j)=>`<button type="button" data-choice="${j}" ${completed(id)?'disabled':''}>${esc(option)}</button>`).join('')}</div><div class="resp-feedback" role="status">${completed(id)?'✓ '+esc(q[3]):''}</div></div>`}).join('')}
function anatomyDiagram(n){if(n===3||n===5)return `<div class="resp-exchange" role="img" aria-label="Gas exchange: oxygen moves from alveolus to blood in lungs then from blood to cells at tissues; carbon dioxide moves back"><div class="resp-sac">ALVEOLUS<br><small>air</small></div><div class="resp-gases"><span>O₂ →</span><span>← CO₂</span></div><div class="resp-blood">CAPILLARY<br><small>blood</small></div>${n===5?'<div class="resp-gases"><span>O₂ →</span><span>← CO₂</span></div><div class="resp-cell">BODY CELL</div>':''}</div>`;if(n===4)return `<div class="resp-pressure" aria-hidden="true"><span>INHALE<br>diaphragm ↓<br>volume ↑ · pressure ↓</span><span>EXHALE<br>diaphragm ↑<br>volume ↓ · pressure ↑</span></div>`;return `<div class="resp-route" aria-label="Airway route">${['Nose / mouth','Pharynx','Larynx','Trachea','Bronchi','Bronchioles','Alveoli'].map(x=>`<span>${x}</span>`).join('<b aria-hidden="true">→</b>')}</div>`}
function landing(){const p=progress();layout(`<section class="resp-world"><div class="resp-hero"><div><div class="eyebrow">SYSTEM 04 — RESPIRATORY SYSTEM</div><h1>Welcome to the Oxygen Mission</h1><p>Follow a breath from the airways to an alveolus, move gases across a capillary, power breathing with the diaphragm and help working cells get oxygen.</p><a class="btn" href="#respiratory/mission/${p.done.length<6?p.done.length+1:6}">${p.done.length?'Continue your expedition':'Begin the First Mission'} →</a><p class="resp-progress">${p.done.length}/6 missions complete · ${percent()}% of this world explored</p></div><div class="resp-hero-art" aria-hidden="true"><span>O₂</span><span>🫁</span><span>CO₂</span></div></div>${bodyAtlasMarkup('respiratory')}<div class="headrow"><div><div class="eyebrow">YOUR LEARNING ROUTE</div><h2>Six missions and a final challenge</h2><p>Complete the interactive lab and three checks in each mission to unlock the next one.</p></div><span class="chip">${p.done.length}/6 fragments</span></div><div class="resp-grid">${titles.map((name,i)=>{let n=i+1,locked=n>1&&!p.done.includes(n-1);return `<article class="panel resp-card ${locked?'resp-locked':''}"><div class="eyebrow">MISSION ${String(n).padStart(2,'0')} ${p.done.includes(n)?'· ✓ COMPLETE':''}</div><h3>${name}</h3><p>${lessons[i].goal}</p>${locked?'<button class="btn line" disabled>Finish the previous mission</button>':`<a class="btn ${p.done.includes(n)?'secondary':''}" href="#respiratory/mission/${n}">${p.done.includes(n)?'Review mission':'Open mission'} →</a>`}</article>`}).join('')}</div><div class="finalmission resp-finale"><div><div class="eyebrow">FINAL CHALLENGE</div><h3>Keep oxygen moving</h3><p>Use all six discoveries to restore a breath-to-cell route.</p></div>${p.done.length===6?'<a class="btn" href="#respiratory/mastery">Start challenge →</a>':'<button class="btn line" disabled>Complete six missions</button>'}</div></section>`);window.mountBodyAtlas?.('respiratory')}
function lab(n){let [name,help,stages]=labs[n-1];return `<section class="panel resp-lab"><div class="eyebrow">INTERACTIVE LAB · ${name.toUpperCase()}</div><h2>${name}</h2><p>${help}</p><div class="resp-lab-visual" id="resp-visual">${anatomyDiagram(n)}</div><div class="resp-lab-controls">${stages.map((s,i)=>`<button type="button" data-lab="${i}" aria-pressed="false">${esc(s[0])}</button>`).join('')}</div><div id="resp-lab-output" role="status">${completed(`${n}-lab`)?'✓ Lab completed. Explore again.':'Select each stage to reveal the whole process.'}</div><div class="resp-lab-count">${completed(`${n}-lab`)?'✓ Discovery saved':'0/'+stages.length+' stages explored'}</div></section>`}
function mission(n){const p=progress();if(!Number.isInteger(n)||n<1||n>6||n>1&&!p.done.includes(n-1)){location.hash='respiratory';return}const d=lessons[n-1],seen=new Set();let finish=()=>{if(completed(`${n}-lab`)&&d.checks.every((_,i)=>completed(`${n}-q${i}`))){if(!p.done.includes(n)){p.done.push(n);save();reward('resp-mission-'+n,25)}document.getElementById('resp-finish').innerHTML=`<div class="feedback">Mission complete. Fragment ${n}/6 secured. <a href="#respiratory/${n===6?'mastery':'mission/'+(n+1)}">${n===6?'Begin the final challenge':'Continue to mission '+(n+1)} →</a></div>`}};
layout(`<div class="resp-world"><a class="textlink" href="#respiratory">← The Oxygen Mission</a><div class="resp-mission-header"><div class="eyebrow">SYSTEM 04 · MISSION ${String(n).padStart(2,'0')}</div><h1>${titles[n-1]}</h1><p>${d.goal}</p></div><div class="resp-columns"><div><section class="panel resp-lesson"><div class="eyebrow">TRACE THE SCIENCE</div><h2>The idea</h2><p>${d.text}</p><p class="hint"><strong>Keep straight:</strong> ${d.mis}</p></section>${lab(n)}<section class="panel resp-checks"><div class="eyebrow">CHECK YOUR UNDERSTANDING</div><h2>Three checks</h2><p>Try each question. Your progress is saved when you find the answer.</p>${questions(n)}<div id="resp-finish"></div></section></div><aside class="panel resp-aside"><h3>Mission guide</h3><p><strong>Goal:</strong> ${d.goal}</p><p><strong>Words:</strong> ${d.terms}</p><p><strong>Think about:</strong> ${d.mis}</p><p><strong>Progress:</strong> ${p.done.includes(n)?'Mission complete':'In progress'}</p><button type="button" class="btn secondary" id="resp-hint">Get a clue</button><div id="resp-hint-output" role="status"></div></aside></div></div>`);
const stages=labs[n-1][2];document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>{const i=+b.dataset.lab;seen.add(i);document.querySelectorAll('[data-lab]').forEach(button=>button.setAttribute('aria-pressed',String(button===b)));document.getElementById('resp-lab-output').textContent=stages[i][1];document.getElementById('resp-visual').dataset.stage=i;const rvis=document.getElementById('resp-visual');if(rvis){const parts=[...rvis.querySelectorAll('.resp-route span,.resp-exchange>div,.resp-pressure>span')];parts.forEach(p=>p.classList.remove('is-active'));if(parts.length){const idx=stages.length>1?Math.round(i/(stages.length-1)*(parts.length-1)):0;parts[idx].classList.add('is-active')}}if(seen.size===stages.length){step(`${n}-lab`,20);document.querySelector('.resp-lab-count').textContent='✓ All stages explored · discovery saved';finish()}else document.querySelector('.resp-lab-count').textContent=`${seen.size}/${stages.length} stages explored`});
document.querySelectorAll('.resp-question').forEach(el=>{const [,q]=el.dataset.question.match(/-q(\d+)$/)||[],qi=+q,item=d.checks[qi],weakId=n+'-q'+qi;el.querySelectorAll('[data-choice]').forEach(button=>button.onclick=()=>{const correct=+button.dataset.choice===item[2],tries=+el.dataset.tries||0;if(!correct)el.dataset.tries=String(tries+1);el.querySelector('.resp-feedback').textContent=correct?'Correct. '+item[3]:(tries<1?'Not yet. Re-read the mission guide, then try again.':'Look again. '+item[3]);el.classList.toggle('resp-wrong',!correct);const pw=progress();if(correct){pw.weak=pw.weak.filter(x=>x!==weakId)}else if(!pw.weak.includes(weakId)){pw.weak.push(weakId)}save();if(correct){el.querySelectorAll('[data-choice]').forEach(x=>x.disabled=true);button.classList.add('resp-correct');step(el.dataset.question,7);finish()}})});document.getElementById('resp-hint').onclick=()=>document.getElementById('resp-hint-output').textContent=d.mis;finish()}
const finalStages=[
 ['A runner inhales. Which route delivers air into the exchange sacs?',['Nose → trachea → bronchi → bronchioles → alveoli','Nose → alveoli → trachea → bronchi'],0,'Air follows progressively smaller branches into the alveoli.'],
 ['Particles enter the nose. Which defense helps?',['Mucus traps them; cilia move them toward the throat','Alveoli pump them into the heart'],0,'The nasal passages and ciliated airways condition and clear air.'],
 ['The diaphragm contracts downward. What follows?',['Volume increases; pressure falls; air flows in','Volume decreases; pressure rises; air flows in'],0,'Expansion lowers pressure and draws air inward.'],
 ['In lung capillaries, where does oxygen go?',['From alveolar air into blood','From blood into alveolar air'],0,'Oxygen diffuses into blood across the thin walls.'],
 ['A working muscle needs oxygen. Where does it go?',['From tissue capillary into cell','From cell into tissue capillary'],0,'Oxygen moves from blood to the cell.'],
 ['That cell makes carbon dioxide. What carries it away?',['Blood returns it to the lungs','The diaphragm turns it into oxygen'],0,'Carbon dioxide enters blood and is transported toward alveoli.'],
 ['Alveolar walls break down. What is directly reduced?',['Gas exchange surface area','Tracheal cartilage only'],0,'Loss of alveolar wall area makes exchange less effective.'],
 ['What produces the cell’s usable energy?',['Cellular respiration using oxygen and glucose','Ventilation alone'],0,'Cells use oxygen and glucose to release ATP.']
];finalStages.forEach((q,i)=>finalStages[i]=mixQ(q));

function mastery(){const p=progress();if(p.done.length<6){location.hash='respiratory';return}layout(`<div class="resp-world"><a class="textlink" href="#respiratory">← The Oxygen Mission</a><div class="resp-mission-header"><div class="eyebrow">SYSTEM 04 · FINAL CHALLENGE</div><h1>Keep oxygen moving</h1><p>Restore the route from a breath to a working cell, then return its carbon dioxide to the air.</p></div><section class="panel resp-checks">${finalStages.map((q,i)=>`<div class="resp-question" data-final="${i}"><div class="eyebrow">STAGE ${i+1}/8</div><h3>${q[0]}</h3><div class="resp-choices">${q[1].map((answer,j)=>`<button type="button" data-choice="${j}" ${completed('final-'+i)?'disabled':''}>${answer}</button>`).join('')}</div><div class="resp-feedback" role="status">${completed('final-'+i)?'✓ '+q[3]:''}</div></div>`).join('')}<div id="resp-mastered"></div></section></div>`);const finish=()=>{if(finalStages.every((_,i)=>completed('final-'+i))){if(!p.mastery){p.mastery=true;save();reward('resp-key',50)}document.getElementById('resp-mastered').innerHTML='<div class="feedback"><h2>Oxygen Mission complete!</h2><p>Every stage is restored. You earned the Respiratory System Key.</p><a href="#respiratory" class="btn secondary">Explore the world again →</a></div>'}};document.querySelectorAll('[data-final]').forEach(el=>{const i=+el.dataset.final,q=finalStages[i];el.querySelectorAll('[data-choice]').forEach(button=>button.onclick=()=>{const good=+button.dataset.choice===q[2];el.querySelector('.resp-feedback').textContent=(good?'Correct. ':'Try again. ')+q[3];el.classList.toggle('resp-wrong',!good);if(good){button.classList.add('resp-correct');el.querySelectorAll('button').forEach(b=>b.disabled=true);step('final-'+i,8);finish()}})});finish()}
const previousPortal=portal;portal=function(i){if(i!==3)return previousPortal(i);const s=systems[i],p=percent();return `<article class="portal world-portal playable" data-card="3" style="--system-color:${s[3]}"><button class="system-select" data-system="3" aria-pressed="false" aria-label="Select Respiratory System"><span class="world-card-top"><span class="system-icon">${systemIcon(3)}</span><span class="world-index">WORLD 04</span></span><span class="world-card-name">OXYGEN</span><span class="scientific-name">Respiratory System</span><span class="ready-label">${p?'Exploration in progress':'Ready to explore'}</span><span class="progress-meta"><span>${p}% complete</span><span>${progress().done.length}/6 missions</span></span><span class="bar"><i style="width:${p}%"></i></span></button><a class="btn enter-world" href="#respiratory">Enter World <span aria-hidden="true">→</span></a></article>`};
const priorHighlight=highlightSystem;highlightSystem=function(i){priorHighlight(i);if(i!==3)return;const panel=document.getElementById('selected-system-panel');panel.innerHTML=`<div class="eyebrow">THE OXYGEN MISSION</div><h2>Respiratory System</h2><p>Trace air, exchange gases, investigate breathing and keep cells supplied.</p><a class="btn selected-enter" href="#respiratory">Enter the Oxygen Mission →</a><button class="clear-selection" aria-label="Show all body systems">Show all systems</button>`;panel.querySelector('.clear-selection').onclick=resetSystem;const tip=document.getElementById('anatomy-tooltip');if(tip)tip.textContent='Enter the Oxygen Mission'};
const priorSelectSystem=selectSystem;selectSystem=function(i){priorSelectSystem(i);if(i===3)document.getElementById('anatomy-tooltip').textContent='Enter the Oxygen Mission'};
const previousHome=home;home=function(){previousHome();const j=document.querySelector('[data-journey="3"]');if(j&&!j.querySelector('.journey-playable'))j.insertAdjacentHTML('beforeend','<b class="journey-playable">PLAYABLE</b>');};
const previousDashboard=dashboard;dashboard=function(){previousDashboard();const p=progress(),section=document.createElement('section');section.className='panel spacer';section.innerHTML=`<div class="eyebrow">SYSTEM 04 — RESPIRATORY SYSTEM</div><h2>The Oxygen Mission</h2><p>${p.done.length}/6 missions complete · ${p.mastery?'System Key earned':'Final challenge awaits'}</p><div class="bar"><i style="width:${percent()}%"></i></div><a class="btn" href="#respiratory">Continue the Oxygen Mission →</a>`;const weakIds=p.weak||[];if(weakIds.length){const rv=document.createElement('p');rv.className='note';rv.innerHTML='Revisit: '+weakIds.map(id=>{const a=id.split('-q').map(Number);return '<a class="textlink" href="#respiratory/mission/'+a[0]+'">'+lessons[a[0]-1].checks[a[1]][0]+'</a>'}).join(' · ');section.append(rv)}
document.getElementById('main').append(section);const reset=document.getElementById('reset');if(reset){const prior=reset.onclick;reset.onclick=()=>{prior();const yes=document.getElementById('confirm-reset');if(yes){const confirmed=yes.onclick;yes.onclick=()=>{state.respiratory={done:[],steps:{},mastery:false};confirmed()}}}}};
const previousBadges=badges;badges=function(){previousBadges();const p=progress();document.getElementById('main').insertAdjacentHTML('beforeend',`<section class="panel spacer"><h2>Oxygen Mission discoveries</h2><div class="resp-grid">${titles.map((title,i)=>`<a class="badge ${p.done.includes(i+1)?'':'locked'}" href="#respiratory/mission/${i+1}"><span>✵</span><h3>${title}</h3><p>${p.done.includes(i+1)?'Earned':'Complete mission '+(i+1)}</p></a>`).join('')}</div><p>${p.mastery?'Respiratory System Key earned.':'Complete all missions and the final challenge to earn the System Key.'}</p></section>`)};
const previousInfo=info;info=function(r){previousInfo(r);if(r==='sources')document.querySelector('#main .sourcelist')?.insertAdjacentHTML('beforeend','<li><b>UAE Inspire Science Biology · Grade 10 General · Respiratory System, supplied lesson pages 35–39.</b><br>Airway, breathing mechanics, gas exchange and respiratory health. Original diagrams; textbook figures are not reproduced.</li><li><b>Original 3D teaching model.</b><br>Sculpted lung surfaces, trachea, branching airways and diaphragm; a magnified alveolar cluster is shown in the 3D explorer.</li>')};
const previousRoute=route;window.removeEventListener('hashchange',previousRoute);route=function(){const hash=location.hash.slice(1);if(hash==='respiratory')landing();else if(hash.startsWith('respiratory/mission/'))mission(Number(hash.split('/')[2]));else if(hash==='respiratory/mastery')mastery();else previousRoute();window.scrollTo(0,0)};window.addEventListener('hashchange',route);route();
})();
